language: python

before_install:
  - wget -q https://storage.googleapis.com/kubernetes-helm/helm-v2.4.1-linux-amd64.tar.gz
  - tar xzfv helm-v2.4.1-linux-amd64.tar.gz
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init
